In [21]:
import numpy as np
from mflex.model.field.utility.poloidal import (
    phi,
    phi_low,
    dphidz,
    dphidz_low,
    phi_hypgeo,
    dphidz_hypgeo,
)

In [22]:
test_arr = np.arange(1, 10, 1)

In [23]:
print(test_arr)

[1 2 3 4 5 6 7 8 9]


In [24]:
a = 3.0

In [25]:
print(a ** test_arr)

[3.0000e+00 9.0000e+00 2.7000e+01 8.1000e+01 2.4300e+02 7.2900e+02
 2.1870e+03 6.5610e+03 1.9683e+04]


In [26]:
test_arr2 = test_arr - 1

In [27]:
print(test_arr2)

[0 1 2 3 4 5 6 7 8]


In [28]:
print(test_arr2+ test_arr)

[ 1  3  5  7  9 11 13 15 17]


In [29]:
nresol_z = 10 
zmax = 2.0
zmin = 0.0 
z_arr = np.arange(nresol_z) * (zmax - zmin) / (nresol_z - 1) + zmin

nf_max = 10 
length_scale_x_norm = 1.0
length_scale_y_norm = 1.0

ratiodzls = 0.02
alpha = 0.25
a = 0.1
b = 1.0

In [30]:
kx_arr = np.arange(nf_max) * np.pi / length_scale_x_norm  # [0:nf_max]
ky_arr = np.arange(nf_max) * np.pi / length_scale_y_norm  # [0:nf_max]
one_arr = 0.0 * np.arange(nf_max) + 1.0

ky_grid = np.outer(ky_arr, one_arr)  # [0:nf_max, 0:nf_max]
kx_grid = np.outer(one_arr, kx_arr)  # [0:nf_max, 0:nf_max]

# kx^2 + ky^2

k2_arr = np.outer(ky_arr**2, one_arr) + np.outer(one_arr, kx_arr**2)
k2_arr[0, 0] = (np.pi / length_scale_x_norm) ** 2 + (
    np.pi / length_scale_y_norm
) ** 2

p_arr = 0.5 * ratiodzls * np.sqrt(k2_arr * (1.0 - a - a * b) - alpha**2)
q_arr = 0.5 * ratiodzls * np.sqrt(k2_arr * (1.0 - a + a * b) - alpha**2)

phi_arr = np.zeros((nf_max, nf_max, nresol_z))
dphidz_arr = np.zeros((nf_max, nf_max, nresol_z))

z0 = 0.2
deltaz = 0.02